version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=paulov
      - POSTGRES_PASSWORD=paulovroot
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=paulos_50@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=paulovroot
    ports:
      - 5050:80

